import "./globals.css";
import Link from "next/link";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href={"/"}>Next App</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
